# fly.toml app configuration file generated for personalizedclothingapi on 2023-11-23T02:42:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personalizedclothingapi"
primary_region = "mia"

[build]

[processes]
  app = "gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 120 --chdir /app/src app:app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
